-- ============================================================
--  Studio Dentistico Rinaldi Montalbano — Supabase setup
--  Run once in: Supabase Dashboard → SQL Editor → New query → Run
--  Safe to re-run (idempotent): uses IF NOT EXISTS / ON CONFLICT.
-- ============================================================

-- ============================================================
--  1. TEAM MEMBERS
-- ============================================================
create table if not exists public.team_members (
  id            uuid primary key default gen_random_uuid(),
  sort_order    int          not null default 0,
  name          text         not null,
  photo_url     text,
  initials      text,
  gradient_from text         default '#D8CFC4',
  gradient_to   text         default '#9E7E3A',
  tag_it        text,
  tag_en        text,
  bio_short_it  text,
  bio_short_en  text,
  bio_long_it   text,
  bio_long_en   text,
  visible       boolean      not null default true,
  created_at    timestamptz  not null default now()
);

create index if not exists team_members_sort_idx on public.team_members (sort_order);

alter table public.team_members enable row level security;

-- anon (public site) can read only visible members
drop policy if exists "team_members public read" on public.team_members;
create policy "team_members public read"
  on public.team_members for select
  to anon
  using (visible = true);

-- authenticated (admin) full access
drop policy if exists "team_members admin all" on public.team_members;
create policy "team_members admin all"
  on public.team_members for all
  to authenticated
  using (true) with check (true);

-- ============================================================
--  2. ANALYTICS EVENTS  (mirrors the RM Bygg / Rezki schema)
-- ============================================================
create table if not exists public.analytics_events (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  session_id  text,
  event_type  text,        -- pageview | section | click | duration | heartbeat | geo
  label       text,
  value       double precision,
  device      text,        -- desktop | mobile
  lang        text,        -- it | en
  city        text,
  region      text,
  country     text,
  latitude    double precision,
  longitude   double precision
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_session_idx    on public.analytics_events (session_id);
create index if not exists analytics_events_type_idx       on public.analytics_events (event_type);

alter table public.analytics_events enable row level security;

-- anon can only INSERT events (never read them)
drop policy if exists "analytics anon insert" on public.analytics_events;
create policy "analytics anon insert"
  on public.analytics_events for insert
  to anon
  with check (true);

-- authenticated (admin) can read them
drop policy if exists "analytics admin read" on public.analytics_events;
create policy "analytics admin read"
  on public.analytics_events for select
  to authenticated
  using (true);

-- ============================================================
--  3. STORAGE BUCKET  team-photos  (public read)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('team-photos', 'team-photos', true)
on conflict (id) do update set public = true;

drop policy if exists "team-photos public read" on storage.objects;
create policy "team-photos public read"
  on storage.objects for select
  to anon
  using (bucket_id = 'team-photos');

drop policy if exists "team-photos admin insert" on storage.objects;
create policy "team-photos admin insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'team-photos');

drop policy if exists "team-photos admin update" on storage.objects;
create policy "team-photos admin update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'team-photos');

drop policy if exists "team-photos admin delete" on storage.objects;
create policy "team-photos admin delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'team-photos');

-- ============================================================
--  4. SEED — the 3 current dentists (only if table is empty)
-- ============================================================
insert into public.team_members
  (sort_order, name, initials, gradient_from, gradient_to,
   tag_it, tag_en, bio_short_it, bio_short_en, bio_long_it, bio_long_en)
select * from (values
  (1, 'Dott. Marcello Rinaldi', 'MR', '#D8CFC4', '#9E7E3A',
   'Fondatore · Implantologia', 'Founder · Implantology',
   $b$Fondatore dello studio nel 2003. Specialista in implantologia e chirurgia orale con oltre 20 anni di esperienza nel territorio romagnolo.$b$,
   $b$Founder of the practice in 2003. Specialist in implantology and oral surgery with over 20 years of experience in the Romagna region.$b$,
   $b$Fondatore dello studio nel 2003, il Dott. Marcello Rinaldi è specialista in implantologia e chirurgia orale con oltre vent'anni di esperienza clinica. Cresciuto e formatosi nel territorio romagnolo, porta in ogni intervento la precisione della specializzazione e il calore di chi conosce i propri pazienti da una vita. È il punto di riferimento per i casi più complessi di chirurgia implantologica, con un approccio diretto, trasparente e sempre orientato al benessere del paziente.$b$,
   $b$Founder of the practice in 2003, Dr Marcello Rinaldi is a specialist in implantology and oral surgery with more than twenty years of clinical experience. Raised and trained in the Romagna region, he brings specialist precision and the warmth of someone who has known his patients for a lifetime to every procedure. He is the reference point for the most complex implant surgery cases, with a direct, transparent approach always focused on patient wellbeing.$b$),

  (2, 'Dott.ssa Clara Montalbano', 'CM', '#EDE0D8', '#C4622D',
   'Ortodonzia · Pedodonzia', 'Orthodontics · Paediatrics',
   $b$Specialista in ortodonzia fissa e mobile, con particolare attenzione ai pazienti in età evolutiva e al trattamento con allineatori trasparenti.$b$,
   $b$Specialist in fixed and removable orthodontics, with particular focus on young patients and clear aligner treatment.$b$,
   $b$Specialista in ortodonzia fissa e mobile, la Dott.ssa Clara Montalbano si distingue per la competenza con gli allineatori trasparenti e per la cura particolare riservata alla pedodonzia. Il suo approccio gentile e rassicurante la rende il riferimento per i pazienti più giovani e per le famiglie che cercano un dentista capace di mettere a proprio agio anche i bambini più timorosi. Porta avanti la propria formazione con costanza, aggiornandosi sulle tecniche ortodontiche più innovative.$b$,
   $b$A specialist in fixed and removable orthodontics, Dr Clara Montalbano is known for her expertise with clear aligners and her special care in paediatric dentistry. Her gentle, reassuring approach makes her a trusted point of reference for younger patients and for families looking for a dentist who can put even the most anxious children at ease. She continues her professional development consistently, keeping up to date with the most innovative orthodontic techniques.$b$),

  (3, 'Dott. Mauro Rinaldi', 'MR', '#C8D4DC', '#1A1410',
   'Protesi · Estetica', 'Prosthetics · Aesthetics',
   $b$Esperto in protesi dentale e riabilitazione orale completa. Si dedica alla ricostruzione estetica e funzionale del sorriso con materiali all'avanguardia.$b$,
   $b$Expert in dental prosthetics and full oral rehabilitation, dedicated to aesthetic and functional smile reconstruction.$b$,
   $b$Il Dott. Mauro Rinaldi è lo specialista dello studio in protesi dentale, riabilitazione orale completa ed estetica del sorriso. Con un occhio attento alle proporzioni e ai dettagli, trasforma sorrisi compromessi in nuove identità utilizzando materiali all'avanguardia e tecnologie digitali per garantire precisione e durata. La sua passione per l'estetica dentale si fonde con una solida competenza clinica, rendendo ogni riabilitazione un progetto su misura per il singolo paziente.$b$,
   $b$Dr Mauro Rinaldi is the practice specialist in dental prosthetics, full oral rehabilitation and smile aesthetics. With a careful eye for proportions and detail, he transforms compromised smiles using advanced materials and digital technologies for precision and durability. His passion for dental aesthetics is grounded in solid clinical expertise, making every rehabilitation a bespoke project for the individual patient.$b$)
) as seed
where not exists (select 1 from public.team_members);
